@baseUrl = http://localhost:3000

#Messages
###List all messages
GET {{baseUrl}}/message/
?limit=10
&offset=1
Authorization: Bearer Here_comes_the_token
# &user=gabriel
###List only one message
GET {{baseUrl}}/message/1
Authorization: Bearer Here_comes_the_token
###Create a message
#For testing whiteList: true
POST {{baseUrl}}/message/
Content-Type: application/json

{
    "text": "Hey Jhon!",
    "fromId": 1,
    "toId": 8
}

###Update a message
PATCH {{baseUrl}}/message/14/
Content-Type: application/json

{
    "text": "I love you my brother S2"
}

###Delete a message
DELETE {{baseUrl}}/message/2/



#Person
###List all people
GET {{baseUrl}}/person/
?limite=10
&offset=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiamhvbjJAZ21haWwuY29tIiwiaWF0IjoxNzU2MTQ3NjQ4LCJleHAiOjE3NTYxNTEyNDgsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.gd71_NjiKf9xCwYWEPAb1AhJvvzru34p4LFHwGARwBs

# &user=gabriel
###List only one message
GET {{baseUrl}}/person/1
###Create a message
#For testing whiteList: true
POST {{baseUrl}}/person/
Content-Type: application/json

{
    "email": "jhon2@gmail.com",
    "name": "Gabriel Rodrigues Fernandes",
    "password": "123456"
}

###Update a person
PATCH {{baseUrl}}/person/1/
Content-Type: application/json

{
    "name": "Gabriel Rodrigues Fernandes",
    "password": "aaaaa"
}

###Delete a person
DELETE {{baseUrl}}/person/7/



###AUTH
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "jhon2@gmail.com",
    "password": "123456"
}



